markdown: kramdown
permalink: /:title.html
relative_permalinks: false

safe: true
lsi: false
#pygments: true

name: ITIN.ua
description: Юридическая помощь в IT Бизнесе - Собираем знания вместе
about: Мы создали itin.com.ua с целью дать ответы пользователям на самые важные и интересные вопросы организации бизнеса в IT-сфере, а также предоставить юридическое сопровождение при необходимости.

admin_email: info@itin.com.ua
book_date: 2015-08-11 00:00:00 +0000

url: http://itin.com.ua

all_countries:
- id: poland
  name: Польша

- id: denmark
  name: Дания

- id: netherlands
  name: Нидерланды
  
- id: united-arab-emirates
  name: ОАЭ
  
- id: ofshori
  name: Оффшоры
  
- id: slovakia
  name: Словакия
  
- id: estoniya
  name: Эстония  

all_categories:
- id: a1
  name: Работа с иностранными компаниями
  url: rabota-s-inostrannimi-kompaniyami.html

- id: a2
  name: Организация бизнеса в Украине
  url: organizatsiya-biznessa-v-ukraine.html

- id: a3
  name: Деятельность предпринимателей
  url: deyatelnost-predprinimatelei.html

- id: a4
  name: Интеллектуальная собственность
  url: zaschita-prav-intellektualnoi-sobstvennosti.html

authors:
  ivan-ivanenko:
    name: Ivan Ivanenko
    job: Программист сайта itin.ua
    image: Ivan.png
    fb: https://www.facebook.com/ivan1.ivanenko
    ln: https://www.linkedin.com/profile/view?id=12440410
    tw:
    g_:
    web: http://foobnix.com
    git: https://github.com/foobnix

  anna-ivanenko:
    name: Анна Иваненко
    job: Юрист
    image: anya.jpg

  katerina-timchenko:
    name: Катерина Тимченко
    job: Юрист
    image: katerina-timchenko.jpg
    fb: https://www.facebook.com/ktimchenko
    ln: https://www.linkedin.com/profile/view?id=42676613&trk=nav_responsive_tab_profile
    tw:
    g_:
    web: http://timchenko.kiev.ua

  aleksei-nikolaenko:
    name: Алексей Николаенко
    job: 
    image: 
    fb: 
    ln: 
    tw:
    g_:
    web: www.novira.ee
    
  katerina-britskaya:
    name: Катерина Тихонова
    job: Юрист
    image: photo.jpg
    web: http://www.laudis.ua/
    
  tak-audit:
    name: Так-аудит
    job: Аудит
    image: tak_audit.jpg
    fb: 
    ln: 
    tw:
    g_:
    web: 
    git: 
    
  tatyana-zhila:
    name: Татьяна Жила
    job: Юрист по интеллектуальной собственности
    image: tatyana-zhila.jpg
    fb: 
    ln: 
    tw:
    g_:
    web: http://www.laudis.ua/
    git: 
    
  oksana-volska:
    name: Оксана Волска
    job: юрист
    image: Screenshot_2015-07-09-11-53-11.png
    fb: 
    ln: 
    tw:
    g_:
    web: http://www.pl-ua-by.com/
    git: 
    
  giya-lezhava:
    name: Гия Лежава
    job: IT-специалист
    image: Giya.jpg
    fb: https://www.facebook.com/george.lezhava?fref=ts
    ln: 
    tw:
    g_:
    web: 
    git: 
    
  konstantin-kozlovskii:
    name: Константин Козловский 
    job: Собственник приложения "EnergyExpress"
    image: KOstya Kozlovsriy.jpg
    fb: https://www.facebook.com/konstantin.kozlovsky?fref=ts
    ln: 
    tw:
    g_:
    web: 
    git: 
    
  aleksander-skakunov:
    name: Александер Скакунов
    job: Программист
    image: Alexander-in-action.png
    fb: 
    ln: 
    tw:
    g_: https://plus.google.com/u/0/100673055889132599356/posts
    web:
    git: 
    
  evgenii-sergeev:
    name: Евгений Сергеев
    job: Консультант
    image: sergeev.jpg
    fb: 
    ln: 
    tw:
    g_:
    web:
    git: 
    
  protteco-trust-company-ltd:
    name: PROTTECO TRUST COMPANY LTD
    job: 
    image: 
    fb: 
    ln: 
    tw:
    g_:
    web: http://www.protteco.com/
    git: 
  
  oksana-kuzyura:
    name: Оксана Кузюра
    job: бухгалтер
    image: okskuz.jpg
    fb: 
    ln: 
    tw:
    g_:
    web: 
    git:
    
  lyubomir-ostapiv:
    name: Любомир Остапів
    job: personalFin blogger
    image: ostapiv.jpg
    fb: https://www.facebook.com/lostapiv
    ln: https://www.linkedin.com/in/lyubomyr?trk=nav_responsive_tab_profile
    tw:
    g_: https://plus.google.com/+LyubomyrOstapiv/posts
    web: http://familybudget.com.ua/author/familybudget/
    web: https://simeinyi-budzhet.ua
    git:
   
  elena-sapko:
    name: Елена Сапко
    job: Советник юр. фирмы Laudis по вопросам налогообложения 
    image: lena.jpg
    fb: 
    ln: 
    tw:
    g_:
    web: 
    git:
    
